packages:
  - apps/*
  - packages/*
catalog:
  oxlint: ^0.16.10
  eslint: ^9.26.0
  lint-staged: ^16.0.0
  "@antfu/eslint-config": ^4.13.1
  tsdown: ^0.11.9
  vitest: ^3.1.3
  typescript: ^5.8.3
  "@clack/prompts": ^0.10.1
  memfs: ^4.17.2
onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
