packages:
  - apps/*
  - packages/*
catalog:
  oxlint: ^0.16.10
  eslint: ^9.26.0
  lint-staged: ^16.0.0
  "@antfu/eslint-config": ^4.13.1
onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
